# Site settings
url: https://lufevida.github.io
baseurl: /html5up-big-picture
title: Context-Aware Hashtag Generation
# author: HTML5 UP

# Intro Section
introTitle: Abstract
introGreeting: Context-Aware Hashtag Generation
sectionOneTitle: The Data
sectionTwoTitle: Architecture
sectionThreeTitle: Challenges
sectionFourTitle: About Us

# Contact information